### ISSUE TITLE
stars

### ISSUE THREAD

**Issue by alxndr** [alxndr/almost-dead-net#415]
like in Dick's notes for the Dead...

change the bullet point??

* from normal to something else...

```css
li.stars-1 { list-style-type: "★"; }
li.stars-2 { list-style-type: "★★"; }
```

![Dick Latvala setlist & notes, 12/6/69](https://i.imgur.com/4JiR1Wq.jpeg)
